clc;
clear all;
close all;
Pt = 65;                
Gt = 4.18;                 
Gr = 4.18;                 
f_MHz = 5000;            
f_Hz = f_MHz * 1e6;
d_km_ref = 800;          
B = 15e6;                
Rb = 6e6;                
T = 290;                
k = 1.38e-23;           
FSPL_ref = 32.44 + 20*log10(f_MHz) + 20*log10(d_km_ref);
Pr_ref = Pt + Gt + Gr - FSPL_ref;
fprintf('Reference FSPL = %.2f dB\n', FSPL_ref);
fprintf('Reference Received Power = %.2f dBm\n\n', Pr_ref);
distance_km = linspace(100, 5000, 200);
FSPL_dist = 32.44 + 20*log10(f_MHz) + 20*log10(distance_km);
figure;
plot(distance_km, FSPL_dist, 'LineWidth', 2);
grid on;
xlabel('Distance (km)');
ylabel('FSPL (dB)');
title('Free Space Path Loss vs Distance');
frequency_MHz = linspace(1000, 20000, 200);
FSPL_freq = 32.44 + 20*log10(frequency_MHz) + 20*log10(d_km_ref);
figure;
plot(frequency_MHz, FSPL_freq, 'LineWidth', 2);
grid on;
xlabel('Frequency (MHz)');
ylabel('FSPL (dB)');
title('Free Space Path Loss vs Frequency');
Pr_dist = Pt + Gt + Gr - FSPL_dist;
figure;
plot(distance_km, Pr_dist, 'LineWidth', 2);
grid on;
xlabel('Distance (km)');
ylabel('Received Power (dBm)');
title('Received Power vs Distance');
Pn = 10*log10(k*T*B);
CN_no_rain = Pr_dist - Pn;
figure;
plot(distance_km, CN_no_rain, 'LineWidth', 2);
grid on;
xlabel('Distance (km)');
ylabel('C/N (dB)');
title('Carrier-to-Noise Ratio vs Distance (No Rain)');
Rain_Att = 5;   
Pr_rain = Pr_dist - Rain_Att;
CN_rain = Pr_rain - Pn;
figure;
plot(distance_km, CN_no_rain, 'LineWidth', 2);
hold on;
plot(distance_km, CN_rain, 'r', 'LineWidth', 2);
grid on;
xlabel('Distance (km)');
ylabel('C/N (dB)');
legend('No Rain', 'With Rain');
title('C/N vs Distance with Rain Effect');
EbN0_no_rain = CN_no_rain - 10*log10(Rb/B);
EbN0_rain = CN_rain - 10*log10(Rb/B);
figure;
plot(distance_km, EbN0_no_rain, 'LineWidth', 2);
hold on;
plot(distance_km, EbN0_rain, 'r', 'LineWidth', 2);
grid on;
xlabel('Distance (km)');
ylabel('Eb/N0 (dB)');
legend('No Rain', 'With Rain');
title('Eb/N0 vs Distance');
Gt_values = 6:2:60;
Pr_gain = Pt + Gt_values + Gr - FSPL_ref;
figure;
plot(Gt_values, Pr_gain, 'LineWidth', 2);
grid on;
xlabel('Transmit Antenna Gain (dBi)');
ylabel('Received Power (dBm)');
title('Effect of Antenna Gain on Received Power');
Pn = 10*log10(k*T*B) + 30;
fprintf('Noise Power Pn = %.2f dBm\n', Pn);
C = Pr_ref;     
CN = C - Pn;
fprintf('C/N = %.2f dB\n', CN);
CN_req = 6;   
CN = Pr_ref - Pn;   
Link_Margin = CN - CN_req;
fprintf('Achieved C/N = %.2f dB\n', CN);
fprintf('Link Margin = %.2f dB\n', Link_Margin);